export type HarnessErrorCode =
  | "BUDGET_CONFIG_INVALID"
  | "BUDGET_EXHAUSTED"
  | "COMPLEXITY_OVERRIDE_INVALID"
  | "DEBUGGING_STATE_INVALID"
  | "GIT_COMMAND_FAILED"
  | "GIT_OUTPUT_INVALID"
  | "PROCESS_CANCELLED"
  | "PROCESS_SPAWN_FAILED"
  | "PROCESS_TIMEOUT"
  | "OPENSPEC_CAPABILITY_MISSING"
  | "OPENSPEC_COMMAND_FAILED"
  | "OPENSPEC_INVALID_JSON"
  | "OPENSPEC_SCHEMA_MISMATCH"
  | "PERSISTENCE_CORRUPT_RECORD"
  | "PERSISTENCE_PATH_INVALID"
  | "PERSISTENCE_UNSUPPORTED_VERSION"
  | "PERSISTENCE_VERSION_INVALID"
  | "RECOVERY_STATE_CONFLICT"
  | "REVIEW_ARTIFACT_INVALID"
  | "REVIEW_MODEL_UNAVAILABLE"
  | "REVIEW_TOOL_DENIED"
  | "VERIFICATION_ARTIFACT_INVALID"
  | "VERIFICATION_NOT_READY"
  | "LIFECYCLE_TRANSITION_INVALID"
  | "MANUAL_CHECKPOINT_CONFIRMED"
  | "MANUAL_CHECKPOINT_INVALID"
  | "MANUAL_CHECKPOINT_MISMATCH"
  | "MANUAL_RESUME_INVALID"
  | "SNAPSHOT_INCONSISTENT"
  | "STATE_OBSERVATION_CONFLICT"
  | "TASK_DOCUMENT_INVALID"
  | "TASK_METADATA_INVALID"
  | "TASK_DAG_IMMUTABLE"
  | "TASK_DAG_INVALID"
  | "TASK_SCHEDULER_INVALID"
  | "TASK_COMPLETION_INVALID"
  | "TASK_OUTCOME_INVALID"
  | "WORKTREE_UNSAFE";

export class HarnessError extends Error {
  readonly code: HarnessErrorCode;
  readonly details: Readonly<Record<string, unknown>>;

  constructor(
    code: HarnessErrorCode,
    message: string,
    details: Readonly<Record<string, unknown>> = {},
    options?: ErrorOptions,
  ) {
    super(message, options);
    this.name = "HarnessError";
    this.code = code;
    this.details = details;
  }
}